/** @type {import('tailwindcss').Config} */

const defaultTheme = require("tailwindcss/defaultTheme");

module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    screens: {
      sm: "520px",
      md: "800px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    extend: {
      backgroundImage: {
        hero_bg: "url(assets/image/bg-layer.svg)",
        construction: "url(assets/image/building.jpeg)",
        contract: "url(assets/image/construction.jpg)",
        oil_gas: "url(assets/image/oil_gas.jpeg)",
        equipments: "url(assets/image/equipments.jpeg)",
        procurements: "url(assets/image/procurements.jpeg)",
        water_project: "url(assets/image/water_project.jpeg)",
        renewable: "url(assets/image/renewable.webp)",
        leasing: "url(assets/image/leasing.jpeg)",
        by_project_start_1: "url(assets/image/by-start-1.jpeg)",
        by_project_start_2: "url(assets/image/by-start-2.jpeg)",
        by_project_start_3: "url(assets/image/by-start-3.jpeg)",
        by_project_start_5: "url(assets/image/by-start-5.jpeg)",
        by_project_start_6: "url(assets/image/by-start-6.jpeg)",
        by_project_start_8: "url(assets/image/by-start-8.jpeg)",
        by_project_start_9: "url(assets/image/by-start-9.jpeg)",
        by_project_start_10: "url(assets/image/by-start-10.jpeg)",
        by_project_start_11: "url(assets/image/by-start-11.jpeg)",
        by_project_start_12: "url(assets/image/by-start-12.jpeg)",
        by_project_start_14: "url(assets/image/by-start-14.jpeg)",
        by_project_start_15: "url(assets/image/by-start-15.jpeg)",
        by_project_start_16: "url(assets/image/by-start-16.jpeg)",
        by_project_start_17: "url(assets/image/by-start-17.jpeg)",
        by_project_start_18: "url(assets/image/by-start-18.jpeg)",
        by_project_start_19: "url(assets/image/by-start-19.jpeg)",
        by_project_start_20: "url(assets/image/by-start-20.jpeg)",
        by_project_start_21: "url(assets/image/by-start-21.jpeg)",
        by_project_1: "url(assets/image/by1.jpeg)",
        by_project_2: "url(assets/image/by2.jpeg)",
        by_project_3: "url(assets/image/by3.jpeg)",
        by_project_4: "url(assets/image/by4.jpeg)",
        by_project_5: "url(assets/image/by5.jpg)",
        by_project_6: "url(assets/image/by6.jpg)",
        by_finishing_1: "url(assets/image/bayelsa/by_finishing_1.JPG)",
        by_finishing_2: "url(assets/image/bayelsa/by_finishing_2.JPG)",
        by_finishing_3: "url(assets/image/bayelsa/by_finishing_3.JPG)",
        by_finishing_4: "url(assets/image/bayelsa/by_finishing_4.JPG)",
        by_finishing_5: "url(assets/image/bayelsa/by_finishing_5.JPG)",
        by_finishing_6: "url(assets/image/bayelsa/by_finishing_6.JPG)",
        by_finishing_7: "url(assets/image/bayelsa/by_finishing_7.JPG)",
        by_finishing_8: "url(assets/image/bayelsa/by_finishing_8.JPG)",
        by_finishing_9: "url(assets/image/bayelsa/by_finishing_9.JPG)",
        by_finishing_10: "url(assets/image/bayelsa/by_finishing_10.JPG)",
        by_finishing_11: "url(assets/image/bayelsa/by_finishing_11.JPG)",
        by_finishing_12: "url(assets/image/bayelsa/by_finishing_12.JPG)",
        by_finishing_13: "url(assets/image/bayelsa/by_finishing_13.jpeg)",
        by_finishing_14: "url(assets/image/bayelsa/by_finishing_14.jpeg)",
        by_finishing_15: "url(assets/image/bayelsa/by_finishing_15.jpeg)",
        by_finishing_16: "url(assets/image/bayelsa/by_finishing_16.jpeg)",
        by_finishing_17: "url(assets/image/bayelsa/by_finishing_17.jpeg)",
        by_finishing_18: "url(assets/image/bayelsa/by_finishing_18.jpeg)",
        by_finishing_19: "url(assets/image/bayelsa/by_finishing_19.jpeg)",
        by_finishing_20: "url(assets/image/bayelsa/by_finishing_20.jpeg)",
        by_finishing_21: "url(assets/image/bayelsa/by_finishing_21.jpeg)",
        by_finishing_22: "url(assets/image/bayelsa/by_finishing_22.jpeg)",
        by_finishing_23: "url(assets/image/bayelsa/by_finishing_23.jpeg)",
        by_finishing_24: "url(assets/image/bayelsa/by_finishing_24.jpeg)",
        by_finishing_25: "url(assets/image/bayelsa/by_finishing_25.jpeg)",
        by_finishing_26: "url(assets/image/bayelsa/by_finishing_26.jpeg)",
        by_finishing_27: "url(assets/image/bayelsa/by_finishing_27.jpeg)",
        by_finishing_28: "url(assets/image/bayelsa/by_finishing_28.jpeg)",
        by_finishing_29: "url(assets/image/bayelsa/by_finishing_29.jpeg)",
        by_finishing_30: "url(assets/image/bayelsa/by_finishing_30.jpeg)",
        kpsl_hotel_1: "url(assets/image/hv1.jpeg)",
        kpsl_hotel_2: "url(assets/image/hv2.jpeg)",
        kpsl_hotel_3: "url(assets/image/hv3.jpeg)",
        kpsl_coza_thumb: "url(assets/image/coza/coza_thumb.png)",
        coza_ilorin_1: "url(assets/image/coza/coza_1.jpg)",
        coza_ilorin_2: "url(assets/image/coza/coza_2.jpg)",
        coza_ilorin_3: "url(assets/image/coza/coza_3.jpg)",
        coza_ilorin_4: "url(assets/image/coza/coza_4.jpg)",
        coza_ilorin_5: "url(assets/image/coza/coza_5.jpg)",
        coza_ilorin_6: "url(assets/image/coza/coza_6.jpg)",
        coza_ilorin_7: "url(assets/image/coza/coza_7.jpg)",
        coza_ilorin_8: "url(assets/image/coza/coza_8.jpg)",
        coza_ilorin_9: "url(assets/image/coza/coza_9.jpg)",
        coza_ilorin_10: "url(assets/image/coza/coza_10.jpg)",
        coza_ilorin_11: "url(assets/image/coza/coza_11.jpg)",
        coza_ilorin_12: "url(assets/image/coza/coza_12.jpg)",
        coza_ilorin_13: "url(assets/image/coza/coza_13.jpg)",
        coza_ilorin_14: "url(assets/image/coza/coza_14.jpg)",
        coza_ilorin_15: "url(assets/image/coza/coza_15.jpg)",
        coza_ilorin_16: "url(assets/image/coza/coza_16.jpg)",
        coza_ilorin_17: "url(assets/image/coza/coza_17.jpg)",
        coza_ilorin_18: "url(assets/image/coza/coza_18.jpg)",
        coza_ilorin_19: "url(assets/image/coza/coza_19.jpeg)",
        coza_ilorin_20: "url(assets/image/coza/coza_20.jpeg)",
        coza_ilorin_21: "url(assets/image/coza/coza_21.jpeg)",
        coza_ilorin_22: "url(assets/image/coza/coza_22.jpeg)",
        coza_ilorin_23: "url(assets/image/coza/coza_23.jpeg)",
        coza_ilorin_24: "url(assets/image/coza/coza_24.jpeg)",
        coza_ilorin_25: "url(assets/image/coza/coza_25.jpeg)",
        coza_ilorin_26: "url(assets/image/coza/coza_26.jpeg)",
        coza_ilorin_27: "url(assets/image/coza/coza_27.jpeg)",
        coza_ilorin_28: "url(assets/image/coza/coza_28.jpeg)",
        coza_ilorin_29: "url(assets/image/coza/coza_29.jpeg)",
        coza_ilorin_30: "url(assets/image/coza/coza_30.jpeg)",
        coza_ilorin_31: "url(assets/image/coza/coza_31.jpeg)",
        coza_ilorin_32: "url(assets/image/coza/coza_32.jpeg)",
        coza_ilorin_33: "url(assets/image/coza/coza_33.jpeg)",
        coza_ilorin_34: "url(assets/image/coza/coza_34.jpeg)",
        coza_ilorin_35: "url(assets/image/coza/coza_35.jpeg)",
        coza_ilorin_36: "url(assets/image/coza/coza_36.jpeg)",
        coza_ilorin_37: "url(assets/image/coza/coza_37.jpeg)",
        coza_ilorin_38: "url(assets/image/coza/coza_38.jpeg)",
        coza_ilorin_39: "url(assets/image/coza/coza_39.jpeg)",
        coza_ilorin_40: "url(assets/image/coza/coza_40.jpeg)",
        coza_ilorin_41: "url(assets/image/coza/coza_41.jpeg)",
        coza_ilorin_42: "url(assets/image/coza/coza_42.jpeg)",
        coza_ilorin_43: "url(assets/image/coza/coza_43.jpeg)",
        coza_ilorin_44: "url(assets/image/coza/coza_44.jpeg)",
        coza_ilorin_45: "url(assets/image/coza/coza_45.jpeg)",
        coza_ilorin_46: "url(assets/image/coza/coza_46.jpeg)",
        coza_ilorin_47: "url(assets/image/coza/coza_47.jpeg)",
        trace_1: "url(assets/image/durumi/trace_1.jpg)",
        trace_2: "url(assets/image/durumi/trace_2.jpg)",
        trace_3: "url(assets/image/durumi/trace_3.jpg)",
        trace_4: "url(assets/image/durumi/trace_4.jpg)",
      },

      fontFamily: {
        sans: ["DM Sans", ...defaultTheme.fontFamily.sans],
        "duplicate-san": "Duplicate Sans",
      },
      spacing: {
        1.25: "0.3125rem",
        3.75: "0.9375rem",
        7.5: "1.875rem",
        12.5: "3.125rem",
        15: "3.75rem",
        25: "6.25rem",
        30: "7.5rem",
        37: "9.375rem",
      },
      colors: {
        // gray
        "gray-25": "#FCFCFD",
        "gray-30": "#667085",

        // success
        "success-25": "#d1fadf",
        "success-50": "#ECFDF3",
        "success-100": "#D1FADF",
        "success-500": "#12B76A",
        "success-600": "#039855",
        "success-700": "#027A48",
        "success-800": "#05603a",

        // primary
        "primary-700": "#00060E",
        "primary-50": "#E7E7E7",
        "primary-600": "#000712",

        // error
        "error-50": "#fef3f2",
        "error-25": "#FFFBFA",
        "error-100": "##FEE4E2",
        "error-300": "#FDA29B",
        "error-600": "#F04438",
        "error-700": "#B42318",

        // blue-gray
        "blue-gray-25": "#FCFCFD",
        "blue-gray-50": "#F8F9FC",
        "blue-gray-700": "#363F72",
        "blue-gray-500": "#4E5BA6",
        "blue-gray-600": "#3E4784",

        "blue-light-700": "#026AA2",
        "blue-light-25": "#F5FBFF",

        // warning
        "warning-50": "#FFFCF5",
        "warning-300": "#FEC84B",
        "warning-500": "#F79009",
        "warning-700": "#B54708",
        primary: "#411011",
        secondary: "#A56A4A",
      },
      fontSize: {
        "1sm": "0.9375rem",
        "8lg": "5.3125rem",
      },
      boxShadow: {
        card: "0px 3px 3px rgba(0, 0, 0, 0.06)",
      },
    },
  },
  plugins: [],
};
